In [ ]:
import numpy as np

# 1. Create a sample 2D array with shape (5, 4)
# The values will be random integers between 0 (inclusive) and 100 (exclusive).
arr = np.random.randint(100, size=(5, 4))
print("Original 2D Array:")
print(arr)
print("-" * 30)

# 2. Calculations
# Calculate the mean of each column (axis=0)
column_means = arr.mean(axis=0)
print("Mean of each column:")
print(column_means)

# Calculate the maximum value in each row (axis=1)
row_maxes = arr.max(axis=1)
print("\nMaximum value of each row:")
print(row_maxes)

# Find the total sum of all elements in the array
total_sum = arr.sum()
print("\nTotal sum of all elements:")
print(total_sum)
print("-" * 30)

# 3. Indexing

sliced_array = arr[0:2, 2:4]
print("First two rows and last two columns (slicing):")
print(sliced_array)

greater_than_50 = arr[arr > 50]
print("\nElements greater than 50 (boolean indexing):")
print(greater_than_50)
print("-" * 30)



Original 2D Array:
[[68 68  0 54]
 [78 10 35 63]
 [91 45 92 45]
 [54 44 28 45]
 [39 76 25 10]]
------------------------------
Mean of each column:
[66.  48.6 36.  43.4]

Maximum value of each row:
[68 78 92 54 76]

Total sum of all elements:
970
------------------------------
First two rows and last two columns (slicing):
[[ 0 54]
 [35 63]]

Elements greater than 50 (boolean indexing):
[68 68 54 78 63 91 92 54 76]
------------------------------
